# Generated by Django 3.1 on 2021-11-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211126_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
