# Generated by Django 3.1 on 2021-11-26 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_movie_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='author',
        ),
    ]
